export const currencies = {
	"USD": {"symbol":"$","name":"United States Dollar"},
	"CAD": {"symbol":"$","name":"Canadian Dollar"},
	"EUR": {"symbol":"€","name":"Euro"},
	"GBP": {"symbol":"£","name":"British Pound"},
	"JPY": {"symbol":"¥","name":"Japanese Yen"},
  "AUD": {"symbol":"$","name":"Australian Dollar"},
  "BRL": {"symbol":"R$","name":"Brazilian Real"},
  "BGN": {"symbol":"лв","name":"Bulgarian Lev"},
  "CNY": {"symbol":"¥","name":"Chinese Yuan"},
  "HRK": {"symbol":"kn","name":"Croatian Kuna"},
  "CZK": {"symbol":"Kč","name":"Czech Koruna"},
  "DKK": {"symbol":"Kr","name":"Danish Krone"},
  "HKD": {"symbol":"$","name":"Hong Kong Dollar"},
  "HUF": {"symbol":"Ft","name":"Hungarian Forint"},
  "INR": {"symbol":"₹","name":"Indian Rupee"},
  "IDR": {"symbol":"Rp","name":"Indonesian Rupiah"},
  "ILS": {"symbol":"₪","name":"Israeli New Sheqel"},
  "MYR": {"symbol":"RM","name":"Malaysian Ringgit"},
  "MXN": {"symbol":"$","name":"Mexican Peso"},
  "NZD": {"symbol":"$","name":"New Zealand Dollar"},
  "NOK": {"symbol":"kr","name":"Norwegian Krone"},
  "PHP": {"symbol":"₱","name":"Philippine Peso"},
  "PLN": {"symbol":"zł","name":"Polish Złoty"},
  "RON": {"symbol":"lei","name":"Romanian Leu"},
  "RUB": {"symbol":"₽","name":"Russian Ruble"},
  "SGD": {"symbol":"$","name":"Singapore Dollar"},
  "ZAR": {"symbol":"R","name":"South African Rand"},
  "KRW": {"symbol":"₩","name":"South Korean Won"},
  "SEK": {"symbol":"kr","name":"Swedish Krona"},
  "CHF": {"symbol":"Fr","name":"Swiss Franc"},
  "THB": {"symbol":"฿","name":"Thai Baht"},
  "TRY": {"symbol":"₺","name":"Turkish Lira"}
};